name: CI

on:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun install --production
            - run: bun test --timeout 10000
